
export const UPDATE_IS_MENU = 'UPDATE_IS_MENU'

export const UPDATE_OVERLAY_VISIBLE = 'UPDATE_OVERLAY_VISIBLE'

export const UPDATE_PAGE_VIEW = 'UPDATE_PAGE_VIEW'

export const UPDATE_SELECT_CITY = 'UPDATE_SELECT_CITY'

export const UPDATE_IS_CITY_PICKER = 'UPDATE_IS_CITY_PICKER'
